### ISSUE TITLE
Newer versions do not have an ARM build

### ISSUE THREAD

**Issue by brainrecall** [pilotak/docker-lirc-watcher#2]
Hello, I tried using docker-lirc-watcher on a Raspberry Pi 3 running latest Raspbian (buster). I used docker-compose with your example, however every attempt to run it gave me several errors:
`lirc    | standard_init_linux.go:219: exec user process caused: exec format error`

After some googling, it looks like it might be because the later versions of docker-lirc-watcher are only being built with the amd64 architecture. I looked at https://hub.docker.com/r/pilotak/lirc-watcher/tags?page=1&ordering=last_updated to see what was available.

After I changed the tag from :latest to :1.0.6 the container seemed to work although it is using 100% CPU, an issue I think you fixed on later versions so maybe I'll try building the current version myself.. Just thought I would let you know. Otherwise, thanks for the hard work!

**Comment by brainrecall** [comment]
For those interested, I was able to build the latest:
`docker build https://github.com/pilotak/docker-lirc-watcher.git -t lirc-watcher`

And then I modified my docker-compose.yml to: `image: lirc-watcher`

**Comment by pilotak** [comment]
It's being cross compiled for raspberry pi. But I will double check that

**Comment by pilotak** [comment]
@brainrecall Fixed

Thanks for spotting it, this kind of error was in all of my docker images you can try tag `latest` or `1.0.10`

**Comment by brainrecall** [comment]
Thanks, new images look good!
